Fixes #143 - Add support for footnotes
unfoldingWord-dev/USFM-Tools pull request #28
Opened 2016-10-07 12:54 UTC by richmahn

2016-10-07 18:45 UTC, phillip-hopper requested changes

2016-10-07 18:45 UTC, phillip-hopper commented on usfm_tools/support/singlehtmlRenderer.py
> +                           format(fkey, footnote['chapter'].lstrip('0'), footnote['verse'].lstrip('0'), footnote['chapter'], footnote['verse'],\
It looks like `footnote['chapter']` and `footnote['verse']` are not used.

2016-10-07 18:49 UTC, richmahn commented on usfm_tools/support/singlehtmlRenderer.py
> +                           format(fkey, footnote['chapter'].lstrip('0'), footnote['verse'].lstrip('0'), footnote['chapter'], footnote['verse'],\
Oh right, changed it to using the fkey in the html string

2016-10-08 16:46 UTC, merged

2016-10-08 16:46 UTC, phillip-hopper commented
@richmahn I need this for publishing, so I went ahead and merged it.