Fix 557 - crash on illegal USFM sequence.
unfoldingWord-dev/USFM-Tools pull request #35
Opened 2017-06-06 16:55 UTC by PhotoNomad0

Changes:
- parseUsfm - added escaping of illegal USFM sequences and then modified '\\\\' to print out as '\\'  
- Added unit test with illegal USFM sequence.

2017-06-06 21:07 UTC, phillip-hopper requested changes

2017-06-06 21:07 UTC, phillip-hopper commented on usfm_tools/support/parseUsfm.py
> +    ret_value = ret_value.replace(u'\\\t', "\\\\\t")
This file is importing `unicode_literals` so all strings are unicode, no need for `u'`.

2017-06-06 21:07 UTC, phillip-hopper commented on usfm_tools/support/parseUsfm.py
> +    ret_value = ret_value.replace(u'\\\t', "\\\\\t")
Also, mixing single and double quotes.

2017-06-07 11:05 UTC, PhotoNomad0 commented on usfm_tools/support/parseUsfm.py
> +    ret_value = ret_value.replace(u'\\\t', "\\\\\t")
Thanks, will fix.

2017-06-07 11:42 UTC, richmahn requested changes
Find this still fails if the \ is at the very last line of the USFM file. Here are the results of my tests:

```
$ git checkout photonomad0/Fix_557/UsfmConversionFails
HEAD is now at 782b57f... Added escape of \ followed by tab and added nobreak space (\xa0) to test text.  Cleanup of text literals

$ cd usfm_tools/support/

$ python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import parseUsfm
>>> parseUsfm.parseString('this is a test \\\nthis is a new line')
[<parseUsfm.TEXTToken object at 0x0000000004508550>, <parseUsfm.EscapedToken object at 0x0000000004508C50>, <parseUsfm.TEXTToken object at 0x0000000004508390>]
>>> parseUsfm.parseString('this is a test \\\n')
[<parseUsfm.TEXTToken object at 0x00000000044FFFD0>, <parseUsfm.EscapedToken object at 0x00000000044FFE10>]
>>> parseUsfm.parseString('this is a test \\')
Expected end of text (at char 15), (line:1, col:16)
'this is a test \\'

$
```

Thus exited on the last command. Is there a way to also let it pass if the last character is a `\`?

2017-06-07 12:15 UTC, PhotoNomad0 commented
@richmahn - thanks for catching that.  Added that to test case and cleanup.

2017-06-07 12:43 UTC, phillip-hopper approved these changes
LGTM 👍

2017-06-07 12:50 UTC, richmahn approved these changes
LGTM

2017-06-07 12:51 UTC, merged